import { parseISO } from 'date-fns/parseISO';
import { format } from 'date-fns/format';
import { CheckCircle, ExternalLink, Loader, XCircle } from 'react-feather';
import { Link } from 'wouter';
import { InternalIdentity } from '@bbat/common/src/types';
import { useGetPayerQuery } from '../../api/payers';
import reportApi, {
  useGetReportsQuery,
  useRefreshReportMutation,
} from '../../api/report';
import { Button } from '@bbat/ui/button';
import { useDialog } from '../../components/dialog';
import { NewDebtLedgerDialog } from '../../components/dialogs/new-debt-ledger-dialog';
import { NewDebtStatusReportDialog } from '../../components/dialogs/new-debt-status-report-dialog';
import { NewPaymentLedgerDialog } from '../../components/dialogs/new-payment-ledger-dialog';
import { ReportHistoryDialog } from '../../components/dialogs/report-history-dialog';
import { Table } from '@bbat/ui/table';
import { ReactNode } from 'react';

const UserLink = ({ id }: { id: InternalIdentity }) => {
  const { data: user } = useGetPayerQuery(id.value);

  return (
    <Link
      onClick={e => e.stopPropagation()}
      to={`/admin/payers/${id.value}`}
      className="flex items-center gap-1"
    >
      {user?.name} <ExternalLink className="h-4 text-blue-500" />
    </Link>
  );
};

export const ReportsListing = () => {
  const { data: reports } = useGetReportsQuery(undefined, {
    pollingInterval: 3000,
  });

  const [getReportLink] = reportApi.endpoints.getReportLink.useLazyQuery();

  const showNewDebtLedgerDialog = useDialog(NewDebtLedgerDialog);
  const showNewPaymentLedgerDialog = useDialog(NewPaymentLedgerDialog);
  const showNewDebtStatusReportDialog = useDialog(NewDebtStatusReportDialog);
  const showReportHistoryDialog = useDialog(ReportHistoryDialog);
  const [refreshReport] = useRefreshReportMutation();

  const handleNewDebtLedger = async () => {
    await showNewDebtLedgerDialog({});
  };

  const handleNewPaymentLedger = async () => {
    await showNewPaymentLedgerDialog({});
  };

  const handleNewDebtStatusReport = async () => {
    await showNewDebtStatusReportDialog({});
  };

  const handleRefreshReport = async (id: string) => {
    await refreshReport(id);
  };

  const handleView = async (id: string) => {
    const result = await getReportLink(id);

    if (result?.data?.url) {
      window.open(result.data.url, '_blank');
    }
  };

  return (
    <>
      <h1 className="mb-5 mt-10 text-2xl">Reports</h1>

      <div className="mb-5 flex gap-3">
        <Button onClick={handleNewDebtLedger}>New Debt Ledger</Button>
        <Button onClick={handleNewPaymentLedger}>New Payment Ledger</Button>
        <Button onClick={handleNewDebtStatusReport}>
          New Debt Status Report
        </Button>
      </div>

      <Table
        persist="reports"
        initialSort={{
          column: 'Identifier',
          direction: 'asc',
        }}
        rows={(reports ?? []).map(r => ({ ...r, key: r.id }))}
        columns={[
          {
            name: 'Identifier',
            getValue: report =>
              report.revision > 1
                ? `${report.humanId} Rev. ${report.revision}`
                : report.humanId,
          },
          {
            name: 'Name',
            getValue: 'name',
          },
          {
            name: 'Generated at',
            getValue: 'generatedAt',
            render: generatedAt =>
              format(parseISO(generatedAt), 'dd.MM.yyyy HH:mm'),
          },
          {
            name: 'Generated by',
            getValue: 'generatedBy',
            render: generatedBy =>
              generatedBy ? <UserLink id={generatedBy} /> : 'Unknown', // format(parseISO(generatedAt), 'dd.MM.yyyy HH:mm'),
          },
          {
            name: 'Status',
            getValue: 'status',
            render: status => (
              <div className="flex items-center gap-1">
                {
                  (
                    {
                      generating: (
                        <Loader className="h-4 animate-[spin_3s_linear_infinite] text-blue-600" />
                      ),
                      failed: <XCircle className="h-4 text-red-600" />,
                      finished: <CheckCircle className="h-4 text-green-600" />,
                    } as Record<string, ReactNode>
                  )[status]
                }
                {status[0].toUpperCase() + status.substring(1)}
              </div>
            ),
          },
          {
            name: '',
            getValue: report => report,
            render: report => (
              <div className="flex gap-3">
                <Button
                  small
                  disabled={report.status !== 'finished'}
                  onClick={() => handleView(report.id)}
                >
                  View
                </Button>
                {report.type && report.options && (
                  <Button
                    secondary
                    small
                    onClick={() => handleRefreshReport(report.id)}
                  >
                    Refresh
                  </Button>
                )}
                {report.history.length > 0 && (
                  <Button
                    secondary
                    small
                    onClick={() => {
                      showReportHistoryDialog({ reports: report.history });
                    }}
                  >
                    History
                  </Button>
                )}
              </div>
            ),
          },
        ]}
      />
    </>
  );
};
